In [1]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:6:2]

array([1, 3, 5])

In [7]:
x1 = np.array(range(0,10))
print(x1)
x1.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [16]:
x=np.arange(4).reshape((2,2))
print(x)

[[0 1]
 [2 3]]


In [17]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [28]:
x = np.ones((1, 3, 2))
print(x)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [31]:
x = np.ones((1, 2, 3))
print(x)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [32]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [33]:
np.ones((2,1))

array([[1.],
       [1.]])

In [34]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [35]:
np.ones((1,2))

array([[1., 1.]])

In [40]:
npone = np.ones((2,3,4))
npone

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])